### ISSUE TITLE
feat: Retrieve more info from servers

### ISSUE THREAD

**Issue by ArjixWasTaken** [cetteup/GameserverLister#23]
Any plans to query the servers for info like the player count?

A project for that already exists but it is kinda old and broken. (python-valve)

**Comment by cetteup** [comment]
Not within this project, no. It's really just about collecting and maintaining servers lists.

You can use the library used by GameserverLister directly if you want to query each individual server, see https://github.com/cetteup/pyvpsq. That will give you player numbers etc.

**Comment by ArjixWasTaken** [comment]
Thx
